services:
  database:
    image: 'postgres:17'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-password}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME:-postgres}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks:
      - nimbus
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis_data:/data'
    networks:
      - nimbus

networks:
  nimbus:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
